import { getMonthRange } from "../../lib/dates.js";
import { getMailer, getMailerFromAddress } from "../../lib/mailer.js";
import {
  beginText,
  createPdfDocument,
  drawLine,
  drawRectangle,
  endText,
  setFont,
  setLeading,
  textAt,
  type PdfPage,
} from "../../lib/pdf.js";
import type { AppPrismaClient } from "../../lib/prisma.js";
import type { MonthlyReportEmailPayload } from "./report.schemas.js";

type ReportEntry = {
  workDate: Date;
  hoursWorked: string;
  location: string;
  notes: string | null;
};

type MonthlyPdfReport = {
  fileName: string;
  pdf: Buffer;
};

type MonthlyEmailReport = {
  recipientEmail: string;
  fileName: string;
  pdf: Buffer;
  workerName: string;
  monthLabel: string;
};

function formatMonthLabel(month: string) {
  const [year, monthIndex] = month.split("-").map(Number);
  return new Intl.DateTimeFormat("en", {
    month: "long",
    year: "numeric",
    timeZone: "UTC",
  }).format(new Date(Date.UTC(year, monthIndex - 1, 1)));
}

function formatDayLabel(value: Date) {
  return value.toISOString().slice(0, 10);
}

function buildPages(userName: string, month: string, entries: ReportEntry[]) {
  const monthLabel = formatMonthLabel(month);
  const totalHours = entries.reduce((sum, entry) => sum + Number(entry.hoursWorked), 0);
  const workedDays = entries.length;
  const dailyAverage = workedDays ? totalHours / workedDays : 0;
  const formatHours = (value: number) => value.toFixed(1).replace(".0", "");

  const createBasePage = (pageNumber: number): PdfPage => {
    const commands = [
      drawLine(40, 804, 555, 804),
      drawLine(40, 70, 555, 70),
      drawRectangle(40, 652, 160, 58),
      drawRectangle(217, 652, 160, 58),
      drawRectangle(394, 652, 161, 58),
      beginText(),
      setFont("sans", 18),
      textAt(40, 780, "Worker Hours Tracker"),
      setFont("sans", 10),
      textAt(40, 763, "Monthly report export"),
      setFont("sans", 12),
      textAt(40, 736, `Worker: ${userName}`),
      textAt(40, 718, `Period: ${monthLabel}`),
      setFont("sans", 9),
      textAt(48, 694, "TOTAL HOURS"),
      setFont("sans", 20),
      textAt(48, 670, `${formatHours(totalHours)}h`),
      setFont("sans", 9),
      textAt(225, 694, "WORKED DAYS"),
      setFont("sans", 20),
      textAt(225, 670, `${workedDays}`),
      setFont("sans", 9),
      textAt(402, 694, "DAILY AVG"),
      setFont("sans", 20),
      textAt(402, 670, `${formatHours(dailyAverage)}h`),
      setFont("mono", 10),
      textAt(48, 630, "DATE        LOCATION                         HOURS  NOTES"),
      textAt(48, 618, "---------------------------------------------------------------------"),
      setFont("sans", 9),
      textAt(40, 52, `Page ${pageNumber}`),
      textAt(460, 52, "Generated by Worker Hours Tracker"),
      endText(),
    ];

    return { commands };
  };

  const pages: PdfPage[] = [];
  let pageNumber = 1;
  let page = createBasePage(pageNumber);
  let y = 600;

  const pushRow = (line: string) => {
    if (y < 94) {
      pages.push(page);
      pageNumber += 1;
      page = createBasePage(pageNumber);
      y = 600;
    }

    page.commands.push(beginText(), setFont("mono", 9), textAt(48, y, line), endText());
    y -= 14;
  };

  if (!entries.length) {
    pushRow("No entries found for this month.");
  } else {
    for (const entry of entries) {
      const location = entry.location.length > 30 ? `${entry.location.slice(0, 27)}...` : entry.location;
      const notes = entry.notes
        ? entry.notes.length > 22
          ? `${entry.notes.slice(0, 19)}...`
          : entry.notes
        : "-";
      pushRow(
        `${formatDayLabel(entry.workDate)}  ${location.padEnd(30, " ")}  ${Number(entry.hoursWorked)
          .toFixed(1)
          .padStart(5, " ")}  ${notes}`,
      );
    }
  }

  pages.push(page);
  return pages;
}

export async function generateMonthlyPdfReport(
  prisma: AppPrismaClient,
  userId: string,
  month: string,
): Promise<MonthlyPdfReport> {
  getMonthRange(month);

  const [user, entries] = await Promise.all([
    prisma.user.findUniqueOrThrow({
      where: {
        id: userId,
      },
      select: {
        name: true,
      },
    }),
    prisma.workEntry.findMany({
      where: {
        userId,
        workDate: {
          gte: getMonthRange(month).start,
          lt: getMonthRange(month).end,
        },
      },
      orderBy: {
        workDate: "asc",
      },
      select: {
        workDate: true,
        hoursWorked: true,
        location: true,
        notes: true,
      },
    }),
  ]);

  const pages = buildPages(
    user.name,
    month,
    entries.map((entry) => ({
      workDate: entry.workDate,
      hoursWorked: entry.hoursWorked.toString(),
      location: entry.location,
      notes: entry.notes,
    })),
  );

  return {
    fileName: `worker-hours-${month}.pdf`,
    pdf: createPdfDocument(pages),
  };
}

async function generateMonthlyEmailReport(
  prisma: AppPrismaClient,
  userId: string,
  payload: MonthlyReportEmailPayload,
): Promise<MonthlyEmailReport> {
  getMonthRange(payload.month);

  const [user, entries] = await Promise.all([
    prisma.user.findUniqueOrThrow({
      where: {
        id: userId,
      },
      select: {
        name: true,
      },
    }),
    prisma.workEntry.findMany({
      where: {
        userId,
        workDate: {
          gte: getMonthRange(payload.month).start,
          lt: getMonthRange(payload.month).end,
        },
      },
      orderBy: {
        workDate: "asc",
      },
      select: {
        workDate: true,
        hoursWorked: true,
        location: true,
        notes: true,
      },
    }),
  ]);

  const pages = buildPages(
    user.name,
    payload.month,
    entries.map((entry) => ({
      workDate: entry.workDate,
      hoursWorked: entry.hoursWorked.toString(),
      location: entry.location,
      notes: entry.notes,
    })),
  );

  return {
    recipientEmail: payload.email,
    fileName: `worker-hours-${payload.month}.pdf`,
    pdf: createPdfDocument(pages),
    workerName: user.name,
    monthLabel: formatMonthLabel(payload.month),
  };
}

export async function sendMonthlyPdfReportByEmail(
  prisma: AppPrismaClient,
  userId: string,
  payload: MonthlyReportEmailPayload,
) {
  const report = await generateMonthlyEmailReport(prisma, userId, payload);
  const transporter = getMailer();
  const from = getMailerFromAddress();

  await transporter.sendMail({
    from,
    to: report.recipientEmail,
    subject: `Worker Hours Report - ${report.monthLabel}`,
    text: [
      `Hello,`,
      ``,
      `Attached is the monthly worker hours report for ${report.workerName}.`,
      `Period: ${report.monthLabel}`,
      ``,
      `This email was generated by Worker Hours Tracker.`,
    ].join("\n"),
    attachments: [
      {
        filename: report.fileName,
        content: report.pdf,
        contentType: "application/pdf",
      },
    ],
  });

  return {
    success: true,
    email: report.recipientEmail,
  };
}
